// Demographic averages from YourMorals.org API (schwartz_values), placeholders pending capture.

const DIMENSIONS = [
  { key: 'power', label: 'Power', short: 'Pow' },
  { key: 'achievement', label: 'Achievement', short: 'Ach' },
  { key: 'hedonism', label: 'Hedonism', short: 'Hed' },
  { key: 'stimulation', label: 'Stimulation', short: 'Sti' },
  { key: 'selfDirection', label: 'Self-Direction', short: 'SD' },
  { key: 'universalism', label: 'Universalism', short: 'Uni' },
  { key: 'benevolence', label: 'Benevolence', short: 'Ben' },
  { key: 'tradition', label: 'Tradition', short: 'Tra' },
  { key: 'conformity', label: 'Conformity', short: 'Con' },
  { key: 'security', label: 'Security', short: 'Sec' },
];

const ZERO = { power: 0, achievement: 0, hedonism: 0, stimulation: 0, selfDirection: 0, universalism: 0, benevolence: 0, tradition: 0, conformity: 0, security: 0 };

const MY_RESULT = {
  label: 'My Result',
  power: 2.5,
  achievement: 5.8,
  hedonism: 5.667,
  stimulation: 6.667,
  selfDirection: 7,
  universalism: 5.333,
  benevolence: 4.556,
  tradition: 2.8,
  conformity: 2,
  security: 2.714,
  color: '#8b2e2e',
};

const YOUR_RESULT_COLOR = '#d4553a';

const MASS_PRESET_LABELS = {
  'low-selfDirection': 'Lowest 10 self-direction (singles + combos)',
  'high-selfDirection': 'Highest 10 self-direction (singles + combos)',
  'low-universalism': 'Lowest 10 universalism (singles + combos)',
  'high-universalism': 'Highest 10 universalism (singles + combos)',
};

const DEMOGRAPHICS = [
  { id: 'male', label: 'Male', category: 'gender', color: '#c45c3e', ...ZERO },
  { id: 'female', label: 'Female', category: 'gender', color: '#d4785a', ...ZERO },
  { id: 'liberal', label: 'Liberal', category: 'political', color: '#a83232', ...ZERO },
  { id: 'conservative', label: 'Conservative', category: 'political', color: '#8b3a2a', ...ZERO },
  { id: 'moderate', label: 'Moderate', category: 'political', color: '#b84848', ...ZERO },
  { id: 'hs', label: 'High school or less', category: 'education', color: '#c96850', ...ZERO },
  { id: 'bachelor', label: 'Bachelor or some college', category: 'education', color: '#9e3a2a', ...ZERO },
  { id: 'graduate', label: 'Graduate degree', category: 'education', color: '#7a2a22', ...ZERO },
  { id: 'white', label: 'White or European American', category: 'race', color: '#d4a090', ...ZERO },
  { id: 'black', label: 'Black or African American', category: 'race', color: '#6b2820', ...ZERO },
  { id: 'hispanic', label: 'Hispanic or Latino/Latinx', category: 'race', color: '#c07858', ...ZERO },
  { id: 'asian', label: 'Asian or Asian American', category: 'race', color: '#b85840', ...ZERO },
  { id: 'age-18-29', label: '18–29', category: 'age', color: '#e8a878', ...ZERO },
  { id: 'age-30-44', label: '30–44', category: 'age', color: '#c85038', ...ZERO },
  { id: 'age-45-64', label: '45–64', category: 'age', color: '#a84030', ...ZERO },
  { id: 'age-65', label: '≥65', category: 'age', color: '#883828', ...ZERO },
  { id: 'not-religious', label: 'Not religious', category: 'religiosity', color: '#d49070', ...ZERO },
  { id: 'slightly', label: 'Slightly religious', category: 'religiosity', color: '#b86048', ...ZERO },
  { id: 'moderately', label: 'Moderately religious', category: 'religiosity', color: '#984838', ...ZERO },
  { id: 'very-religious', label: 'Very religious', category: 'religiosity', color: '#783028', ...ZERO },
];

// Multi-filter averages from YourMorals API (key = sorted demographic ids). Placeholder zeros pending capture.
const DEMOGRAPHIC_COMBOS = {
  'age-18-29,bachelor': { ...ZERO },
  'age-18-29,conservative': { ...ZERO },
  'age-18-29,female': { ...ZERO },
  'age-18-29,hs': { ...ZERO },
  'age-18-29,liberal': { ...ZERO },
  'age-18-29,male': { ...ZERO },
  'age-18-29,moderate': { ...ZERO },
  'age-18-29,moderately': { ...ZERO },
  'age-18-29,not-religious': { ...ZERO },
  'age-18-29,slightly': { ...ZERO },
  'age-18-29,white': { ...ZERO },
  'age-30-44,asian': { ...ZERO },
  'age-30-44,bachelor': { ...ZERO },
  'age-30-44,conservative': { ...ZERO },
  'age-30-44,female': { ...ZERO },
  'age-30-44,graduate': { ...ZERO },
  'age-30-44,hs': { power: 1.977, achievement: 4.359, hedonism: 4.085, stimulation: 3.624, selfDirection: 4.92, universalism: 4.297, benevolence: 4.095, tradition: 2.007, conformity: 2.978, security: 3.513 },
  'age-30-44,liberal': { ...ZERO },
  'age-30-44,male': { ...ZERO },
  'age-30-44,moderate': { ...ZERO },
  'age-30-44,moderately': { ...ZERO },
  'age-30-44,not-religious': { ...ZERO },
  'age-30-44,slightly': { ...ZERO },
  'age-30-44,very-religious': { ...ZERO },
  'age-30-44,white': { ...ZERO },
  'age-45-64,bachelor': { ...ZERO },
  'age-45-64,conservative': { ...ZERO },
  'age-45-64,female': { ...ZERO },
  'age-45-64,graduate': { ...ZERO },
  'age-45-64,liberal': { ...ZERO },
  'age-45-64,male': { ...ZERO },
  'age-45-64,moderate': { ...ZERO },
  'age-45-64,moderately': { ...ZERO },
  'age-45-64,not-religious': { ...ZERO },
  'age-45-64,slightly': { ...ZERO },
  'age-45-64,very-religious': { ...ZERO },
  'age-45-64,white': { ...ZERO },
  'age-65,bachelor': { ...ZERO },
  'age-65,female': { ...ZERO },
  'age-65,graduate': { ...ZERO },
  'age-65,liberal': { ...ZERO },
  'age-65,male': { ...ZERO },
  'age-65,not-religious': { ...ZERO },
  'age-65,slightly': { ...ZERO },
  'age-65,white': { ...ZERO },
  'asian,bachelor': { ...ZERO },
  'asian,female': { ...ZERO },
  'asian,graduate': { ...ZERO },
  'asian,hs': { ...ZERO },
  'asian,liberal': { ...ZERO },
  'asian,male': { ...ZERO },
  'asian,moderately': { power: 3.963, achievement: 5.062, hedonism: 4.378, stimulation: 4.213, selfDirection: 5.097, universalism: 4.809, benevolence: 5.169, tradition: 4.289, conformity: 4.983, security: 4.841 },
  'asian,not-religious': { ...ZERO },
  'asian,slightly': { power: 3.114, achievement: 4.749, hedonism: 4.162, stimulation: 3.791, selfDirection: 4.902, universalism: 4.404, benevolence: 4.501, tradition: 2.933, conformity: 3.914, security: 4.214 },
  'bachelor,female': { ...ZERO },
  'bachelor,conservative': { ...ZERO },
  'bachelor,hispanic': { ...ZERO },
  'bachelor,liberal': { ...ZERO },
  'bachelor,black': { power: 2.517, achievement: 4.846, hedonism: 4.251, stimulation: 3.64, selfDirection: 5.186, universalism: 4.753, benevolence: 4.821, tradition: 3.146, conformity: 4.166, security: 4.294 },
  'bachelor,male': { ...ZERO },
  'bachelor,moderate': { ...ZERO },
  'bachelor,moderately': { ...ZERO },
  'bachelor,not-religious': { ...ZERO },
  'bachelor,slightly': { ...ZERO },
  'bachelor,very-religious': { ...ZERO },
  'bachelor,white': { ...ZERO },
  'black,female': { power: 2.526, achievement: 4.913, hedonism: 4.245, stimulation: 3.642, selfDirection: 5.215, universalism: 4.855, benevolence: 4.971, tradition: 3.267, conformity: 4.279, security: 4.33 },
  'black,graduate': { ...ZERO },
  'black,hs': { ...ZERO },
  'black,liberal': { power: 2.294, achievement: 4.768, hedonism: 4.198, stimulation: 3.618, selfDirection: 5.168, universalism: 4.921, benevolence: 4.689, tradition: 2.667, conformity: 3.702, security: 4.043 },
  'black,male': { power: 2.478, achievement: 4.758, hedonism: 4.101, stimulation: 3.61, selfDirection: 5.077, universalism: 4.498, benevolence: 4.488, tradition: 2.722, conformity: 3.788, security: 4.086 },
  'black,moderately': { ...ZERO },
  'black,not-religious': { ...ZERO },
  'conservative,female': { ...ZERO },
  'conservative,graduate': { ...ZERO },
  'conservative,hispanic': { ...ZERO },
  'conservative,hs': { power: 2.698, achievement: 4.584, hedonism: 3.396, stimulation: 3.17, selfDirection: 4.66, universalism: 3.549, benevolence: 4.568, tradition: 3.311, conformity: 4.272, security: 4.316 },
  'conservative,male': { ...ZERO },
  'conservative,moderately': { ...ZERO },
  'conservative,not-religious': { ...ZERO },
  'conservative,slightly': { ...ZERO },
  'conservative,very-religious': { power: 2.225, achievement: 4.348, hedonism: 2.778, stimulation: 2.729, selfDirection: 4.441, universalism: 3.606, benevolence: 5.205, tradition: 3.925, conformity: 4.547, security: 4.207 },
  'conservative,white': { ...ZERO },
  'female,graduate': { ...ZERO },
  'female,hs': { ...ZERO },
  'female,hispanic': { ...ZERO },
  'female,liberal': { ...ZERO },
  'female,moderate': { ...ZERO },
  'female,moderately': { ...ZERO },
  'female,not-religious': { ...ZERO },
  'female,slightly': { ...ZERO },
  'female,very-religious': { ...ZERO },
  'female,white': { ...ZERO },
  'graduate,hispanic': { power: 2.166, achievement: 4.483, hedonism: 3.661, stimulation: 3.399, selfDirection: 4.934, universalism: 4.513, benevolence: 4.524, tradition: 2.505, conformity: 3.415, security: 3.866 },
  'graduate,liberal': { ...ZERO },
  'graduate,male': { ...ZERO },
  'graduate,moderate': { ...ZERO },
  'graduate,moderately': { ...ZERO },
  'graduate,not-religious': { ...ZERO },
  'graduate,slightly': { ...ZERO },
  'graduate,very-religious': { ...ZERO },
  'graduate,white': { ...ZERO },
  'hispanic,hs': { ...ZERO },
  'hispanic,liberal': { ...ZERO },
  'hispanic,male': { ...ZERO },
  'hispanic,moderate': { ...ZERO },
  'hispanic,not-religious': { ...ZERO },
  'hs,liberal': { ...ZERO },
  'hs,male': { ...ZERO },
  'hs,moderate': { ...ZERO },
  'hs,not-religious': { ...ZERO },
  'hs,slightly': { ...ZERO },
  'hs,white': { ...ZERO },
  'hs,very-religious': { ...ZERO },
  'liberal,male': { ...ZERO },
  'liberal,moderately': { ...ZERO },
  'liberal,not-religious': { ...ZERO },
  'liberal,slightly': { ...ZERO },
  'liberal,very-religious': { power: 1.758, achievement: 4.144, hedonism: 3.123, stimulation: 2.961, selfDirection: 4.592, universalism: 4.824, benevolence: 5, tradition: 3.067, conformity: 3.503, security: 3.663 },
  'liberal,white': { ...ZERO },
  'male,moderate': { ...ZERO },
  'male,moderately': { ...ZERO },
  'male,not-religious': { ...ZERO },
  'male,slightly': { ...ZERO },
  'male,very-religious': { ...ZERO },
  'male,white': { ...ZERO },
  'moderate,moderately': { ...ZERO },
  'moderate,not-religious': { ...ZERO },
  'moderate,slightly': { ...ZERO },
  'moderate,very-religious': { power: 2.383, achievement: 4.475, hedonism: 3.212, stimulation: 3.245, selfDirection: 4.664, universalism: 4.457, benevolence: 5.221, tradition: 3.835, conformity: 4.331, security: 4.193 },
  'moderate,white': { ...ZERO },
  'moderately,white': { ...ZERO },
  'not-religious,white': { ...ZERO },
  'slightly,white': { ...ZERO },
  'very-religious,white': { ...ZERO },
};

const DEMOGRAPHIC_NO_DATA = new Set([
  'age-18-29,asian',
  'age-18-29,black',
  'age-18-29,graduate',
  'age-18-29,hispanic',
  'age-18-29,very-religious',
  'age-30-44,black',
  'age-30-44,hispanic',
  'age-45-64,asian',
  'age-45-64,black',
  'age-45-64,hispanic',
  'age-45-64,hs',
  'age-65,asian',
  'age-65,black',
  'age-65,conservative',
  'age-65,hispanic',
  'age-65,hs',
  'age-65,moderately',
  'age-65,moderate',
  'age-65,very-religious',
  'asian,conservative',
  'asian,hs',
  'asian,moderate',
  'asian,very-religious',
  'black,conservative',
  'black,graduate',
  'black,hs',
  'black,moderate',
  'black,moderately',
  'black,not-religious',
  'black,slightly',
  'black,very-religious',
  'conservative,hispanic',
  'hispanic,hs',
  'hispanic,moderate',
  'hispanic,moderately',
  'hispanic,slightly',
  'hispanic,very-religious',
  'hs,moderately',
  'hs,very-religious',
]);

const DEMOGRAPHIC_NOT_ENOUGH = new Set([]);

const DEMOGRAPHIC_COLUMNS = [
  {
    categories: [
      { key: 'gender', title: 'Gender' },
      { key: 'age', title: 'Age' },
      { key: 'religiosity', title: 'Religiosity' },
    ],
  },
  {
    categories: [
      { key: 'political', title: 'Political Ideology' },
      { key: 'education', title: 'Education' },
      { key: 'race', title: 'Race' },
    ],
  },
];

function saveVisitorResults(scores) {
  localStorage.setItem('sv-visitor-results', JSON.stringify(scores));
}

function loadVisitorResults() {
  try {
    const raw = localStorage.getItem('sv-visitor-results');
    if (raw) return JSON.parse(raw);
  } catch (_) { /* ignore */ }
  return null;
}

function clearVisitorResults() {
  localStorage.removeItem('sv-visitor-results');
}
